language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_script:
- set
before_install:
- npm install -g swagger
install:
- npm install
notifications:
  email:
    recipients:
    - bsjun@kr.ibm.com
    on_success: change
    on_failure: always
